name: pinact (Dispatch)

on:
  workflow_dispatch:

jobs:
  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: ${{ vars.ACTIONS_APP_ID }}
          private-key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: suzuki-shunsuke/pinact-action@cf51507d80d4d6522a07348e3d58790290eaf0b6 # v2.0.0
        with:
          app_id: ${{ vars.ACTIONS_APP_ID }}
          app_private_key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}
          skip_push: "true"

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: chore/pinact
          title: "chore: pin GitHub Actions to commit SHAs"
          body: "Automatically generated by pinact via workflow_dispatch."
          commit-message: "chore: pin GitHub Actions to commit SHAs"
